### ISSUE TITLE
Sniffnet is closing itself on open v1.2.0 (MacOS)

### ISSUE THREAD

**Issue by itfidele** [GyulyVGC/sniffnet#196] opened 2023-05-19 07:13 UTC
**To Reproduce**
1. Download to MacOs Setup V1.1.4
2. Install
3. Try to open sniffnet
4. it prompt you to enter password 
5. now it breaks and close back 

**Expected behavior**
expected to start using the app after installation

**Desktop**
 - OS: MacOS Montrey Version 12.6

**Comment by GyulyVGC** [comment] 2023-05-19 07:19
Thanks for reporting!
The problem is basically the same as before, now you just don't see the terminal.
To verify that the problem is the same, please type
`sudo /*/Sniffnet.app/Contents/MacOS/sniffnet`

**Comment by itfidele** [comment] 2023-05-19 07:47
Yes, it returns the same, Thank you for this good work

**Comment by GyulyVGC** [comment] 2023-05-19 09:18
Thanks for having verified. I close this as a duplicate of #176 
I will try to understand what the cause could be and let you know if I have updates.

**Closed by GyulyVGC** 2023-05-19 09:18 UTC
