### ISSUE TITLE
ALSA function 'snd_pcm_open' failed with error 'EHOSTDOWN: Host is down'

### ISSUE THREAD

**Issue by koutheir** [GyulyVGC/sniffnet#224] opened 2023-05-28 16:06 UTC
The application crashes when I try to raise the notification volume:

```plain
thread 'thread_play_sound' panicked at 'called `Result::unwrap()` on an `Err` value:
DefaultStreamConfigError(BackendSpecific { err: BackendSpecificError { 
    description: "ALSA function 'snd_pcm_open' failed with error 'EHOSTDOWN: Host is down'" 
} })',
src/notifications/types/sound.rs:61:72
```

**To Reproduce**

1. Open the application.
2. Enter the password for sudo.
3. Click on the settings button.
4. Slide the notification volume to the right (for a higher volume).
5. The application crashes.

**Expected behavior**

The application should continue running.

**Crash log**
Here it is: [crash.log](https://github.com/GyulyVGC/sniffnet/files/11585044/crash.log)

**Environment**

- Version: 1.2.0
- OS: Debian Linux 12. Linux 6.1.0.

**Comment by koutheir** [comment] 2023-05-28 16:09
If it helps:
- libasound2 version 1.2.8
- pipewire version 0.3.65
- pulseaudio is **not** installed
- KDE version 5.27.2

**Comment by GyulyVGC** [comment] 2023-05-28 16:12
It crashes at [this line](https://github.com/GyulyVGC/sniffnet/blob/main/src/notifications/types/sound.rs#L61).
It seems it cannot find the default output device for audio.
I can suggest you to verify that libasound2-dev is installed and updated to the latest version.

**Comment by koutheir** [comment] 2023-05-28 16:14
```sh
❯ apt show libasound2-dev
Package: libasound2-dev
Version: 1.2.8-1+b1
Priority: optional
Section: libdevel
Source: alsa-lib (1.2.8-1)
Maintainer: Debian ALSA Maintainers <pkg-alsa-devel@lists.alioth.debian.org>
Installed-Size: 677 kB
Provides: libasound-dev
Depends: libasound2 (= 1.2.8-1+b1)
Suggests: libasound2-doc
Homepage: https://www.alsa-project.org/
Tag: devel::library, role::devel-lib, works-with::audio
Download-Size: 110 kB
APT-Manual-Installed: yes
APT-Sources: https://deb.debian.org/debian testing/main amd64 Packages
...
```

**Comment by GyulyVGC** [comment] 2023-05-28 16:16
I forgot to mention that I built the DEB package on ubuntu-latest, which has already caused some problems of compatibility with Debian in the past.
Did you install Sniffnet from the DEB package?

**Comment by koutheir** [comment] 2023-05-28 16:16
![Screenshot_20230528_121522](https://github.com/GyulyVGC/sniffnet/assets/1145849/cb87c1e3-6456-439b-b6e2-56d2e706a28a)

**Comment by koutheir** [comment] 2023-05-28 16:16
>  Did you install Sniffnet from the DEB package?

Yes.

**Comment by koutheir** [comment] 2023-05-28 16:17
```sh
❯ sha256sum Sniffnet_Linux.deb
8c7b93d35f00fea47077688e7642f4c8dac2826e294aa503c500fb7a4b19d369  Sniffnet_Linux.deb
```

**Comment by GyulyVGC** [comment] 2023-05-28 16:18
> > Did you install Sniffnet from the DEB package?
> 
> Yes.

I suspect that could be the problem then.
If you have Rust installed, you could try directly building from source with cargo.

**Comment by koutheir** [comment] 2023-05-28 16:18
>  If you have Rust installed, you could try directly building from source with cargo.

I have it installed. Would installing using `cargo` also set up menu items and the like?

**Comment by GyulyVGC** [comment] 2023-05-28 16:21
Installing from cargo would just build and install the binary to be run from CLI.
Also, you would have to ensure to delete the previous version coming from the DEB package which is in `usr/bin` to be sure to launch the cargo version when typing `sudo sniffnet` from terminal.

**Comment by GyulyVGC** [comment] 2023-05-28 16:22
I don't know if building locally with cargo can solve the issue, but I think it's worth trying

**Comment by koutheir** [comment] 2023-05-28 16:29
I uninstalled the APT package, then run `cargo install sniffnet`. Then:
```sh
❯ which sniffnet
/home/koutheir/.cargo/bin/sniffnet
```

Running sniffnet from a terminal **without sudo** does not reproduce the issue.

Running it **with sudo** reproduces the issue, but now with a different error:
```sh
❯ sudo sniffnet
[sudo] password for koutheir: 
...
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
fish: Job 1, 'sudo sniffnet' terminated by signal SIGFPE (Floating point exception)
```

Is the problem that `sudo` removes a lot of environment variables that are required for ALSA to work?

**Comment by koutheir** [comment] 2023-05-28 16:31
Running the application with `su` instead of `sudo` fixes the issue, because the environment variables are kept.

**Comment by koutheir** [comment] 2023-05-28 16:32
Is there a way to avoid running the application as `root`?

**Comment by koutheir** [comment] 2023-05-28 16:38
This fixes the issue:
```sh
❯ sudo -E sniffnet
```

Can you please update the shortcuts in the `.deb` package to pass the `-E` option to `sudo` when running the application?

**Comment by koutheir** [comment] 2023-05-28 16:40
Ideally, the application should not run as `root`. If you need some `root` capabilities, then running a small daemon as `root` and communicating with that is far more secure.

**Comment by GyulyVGC** [comment] 2023-05-28 16:45
> This fixes the issue:
> 
> ```sh
> 
> ❯ sudo -E sniffnet
> 
> ```
> 
> 
> 
> Can you please update the shortcuts in the `.deb` package to pass the `-E` option to `sudo` when running the application?
> 
> 

Thanks very much for having spotted the cause.
Of course I will update it before the next release.

You can also avoid running the app as sudo by giving Sniffnet privileges to inspect network adapter with:

sudo setcap cap_net_raw,cap_net_admin=eip <your/Sniffnet/executable/path>

**Comment by koutheir** [comment] 2023-05-28 19:18
> You can also avoid running the app as sudo by giving Sniffnet privileges to inspect network adapter with:
>
> sudo setcap cap_net_raw,cap_net_admin=eip <your/Sniffnet/executable/path>

Why didn't the `.deb` package do that to the executable at installation time? Why does the desktop menu shortcut run it with sudo instead?

**Comment by GyulyVGC** [comment] 2023-05-28 19:33
I didn't dig into a way to do that and I must admit that packages are still in a pretty basic form.

If you know how to do that and would like to help, you can edit the resources/sniffnet.desktop folder and submit a PR.

**Comment by koutheir** [comment] 2023-05-28 20:32
I never did that before, but I know it is possible because a Debian package can run a shell script as root during installation after files are copied in place. Once that is done, the `.desktop` file wouldn't need to run the application as root.

**Comment by koutheir** [comment] 2023-05-28 20:37
How do you generate the `.deb` packages?

**Comment by GyulyVGC** [comment] 2023-05-29 08:03
With an automated GitHub workflow (.github/workflows/package.yml)

**Comment by GyulyVGC** [comment] 2023-05-29 08:03
> I never did that before, but I know it is possible because a Debian package can run a shell script as root during installation after files are copied in place.

I can try to better document myself then

**Comment by koutheir** [comment] 2023-05-29 17:31
I found out that you're using `cargo deb` to generate the `.deb` file. As far as I understand, `cargo deb` supports specifying a [`postinst` script](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html) by setting the [`maintainer-scripts` key](https://github.com/kornelski/cargo-deb#packagemetadatadeb-options) inside `[package.metadata.deb]`.

**Comment by 4r7if3x** [comment] 2023-06-01 02:54
This issue has been addressed in my incoming PR. (#228 is also considered)

**Comment by GyulyVGC** [comment] 2023-06-01 06:59
> This issue has been addressed in my incoming PR. (#228 is also considered)

Tyvm ❤️

**Comment by GyulyVGC** [comment] 2023-06-07 21:16
Hey @koutheir 

We changed the building strategy and we are looking for feedback/testers to see if we finally solved this issue.

Could you kindly try the new package available below?

[Sniffnet_LinuxDEB_amd64.deb.zip](https://github.com/GyulyVGC/sniffnet/files/11681994/Sniffnet_LinuxDEB_amd64.deb.zip)

Thanks in advance.

**Comment by koutheir** [comment] 2023-06-08 13:11
Installing works and the issue is fixed.

Also:
```
$ getcap /usr/bin/sniffnet
/usr/bin/sniffnet cap_net_admin,cap_net_raw=eip
$ grep '^Exec=' /usr/share/applications/sniffnet.desktop
Exec=/usr/bin/sniffnet
```

So the executable capabilities are set correctly and `sudo` is not used.

**Closed** 2023-06-08 14:35 UTC
Labels: bug, Linux
