### ISSUE TITLE
Is there a web version of sniffnet besides the client?

### ISSUE THREAD

**Issue by w2234f** [GyulyVGC/sniffnet#375] opened 2023-09-13 02:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Is there a web version of sniffnet besides the client?

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

**Comment by GyulyVGC** [comment] 2023-09-13 09:37
Hi @w2234f 
Currently there is not a web version of Sniffnet.
Closing this issue as a duplicate of #57.

**Closed by GyulyVGC** 2023-09-13 09:37 UTC
