### ISSUE TITLE
sniffnet: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kdipto1** [GyulyVGC/sniffnet#242] opened 2023-06-03 06:52 UTC
**Describe the bug**
I installed the deb package. Also i have installed  the dependencies. But its showing this error :-
sniffnet: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : 22.04

**Comment by GyulyVGC** [comment] 2023-06-03 08:24
Duplicate of #199 and #225.
Please refer to #199.
We hope to fix this issue for the next release.

**Closed** 2023-06-08 14:35 UTC
Labels: duplicate, missing dependency, Linux
