### ISSUE TITLE
ENH: Show list of options in dropdown filters: e.g. Country, domain name etc.

### ISSUE THREAD

**Issue by corneliusroemer** [GyulyVGC/sniffnet#552] opened 2024-07-04 11:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

Add a dropdown of all the matching filter items present in the current dataset for a filter, when initially focusing a filter textbox.

Like this (it's a combobox with immediate mode, from headless ui what i'm showing, but what matters is the UI concept, not the implementation):
![2024-07-04 13 31 43](https://github.com/GyulyVGC/sniffnet/assets/25161793/11c496d3-a17c-4051-a26e-326a0751dc70)

### Is your feature request related to a problem?

I'm always frustrated when I need to type out a string to filter something down, instead of being able to just click and pick from a short list of e.g. country codes or domain names.

This feature would be useful for these filter boxes for example:
![2024-07-04 13 37 39](https://github.com/GyulyVGC/sniffnet/assets/25161793/ef65625b-4e6c-4539-8d5a-c966f621646c)

**Comment by GyulyVGC** [comment] 2024-07-04 13:05
Thanks for the suggestion!

This is a duplicate of another issue (#354) and it's also tracked in the project's [roadmap](https://github.com/GyulyVGC/sniffnet/blob/main/ROADMAP.md).

**Closed by GyulyVGC** 2024-07-04 13:05 UTC
Labels: duplicate, enhancement

**Comment by corneliusroemer** [comment] 2024-07-06 20:47
I'm sorry I missed it's a duplicate. Would be great if Github was better at suggesting duplicates once one has started writing an issue, like Stackoverflow does.

**Comment by GyulyVGC** [comment] 2024-07-06 20:55
No worries!
