### ISSUE TITLE
安装后无法打开

### ISSUE THREAD

**Issue by star2k** [GyulyVGC/sniffnet#358] opened 2023-08-28 02:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

![Snipaste_2023-08-28_10-32-06](https://github.com/GyulyVGC/sniffnet/assets/9582078/8063ddbf-2084-4061-807f-6fb5a8bb4076)
Can't run after installation, as shown in the figure.

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by goodrabbit** [comment] 2023-08-28 03:33
Same Issue, waiting for answer, thanks.

**Comment by goodrabbit** [comment] 2023-08-28 03:46
Please check author's README.md, you may see the answer as followed:
![image](https://github.com/GyulyVGC/sniffnet/assets/5088561/a6206872-a613-4500-b8de-12d59168070e)

**Comment by GyulyVGC** [comment] 2023-08-28 07:24
I confirm that the problem is that you have to install Npcap as described in the README.
Remember to install it in WinPcap API-Compatible mode when requested.
Closing as duplicate of other issues.

**Closed by GyulyVGC** 2023-08-28 07:24 UTC
