### ISSUE TITLE
Windows 11 App Interface Gliches out graphics

### ISSUE THREAD

**Issue by wisehackermonkey** [GyulyVGC/sniffnet#313] opened 2023-07-17 01:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

![image](https://github.com/GyulyVGC/sniffnet/assets/29699356/7ff9ecfb-86c4-4382-92df-c7e27644d328)
# when opening the app:
all the graphics get all weirdly streached out. both in full screen and small size. 
![image](https://github.com/GyulyVGC/sniffnet/assets/29699356/cf796367-f66b-4a44-a176-1c9f2c9e1e5d)
if i move the mouse the large stretched letters move around and glitch out. making the app unuseable

Manufacturer        : Dell Inc.
Model               : XPS 13 9380
TotalPhysicalMemory : 16912322560
WindowsVersion      : 2009

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment] 2023-07-17 06:03
Hi @wisehackermonkey 

Check #312 for the solution

**Comment by GyulyVGC** [comment] 2023-07-17 06:04
From #312:

> This is due to incompatibilities between your graphical adapter and wgpu, the default renderer used by iced.
The problem is usually solved by using an alternative renderer (glow).
Here you are the download link for the Windows version of Sniffnet using it: https://github.com/GyulyVGC/sniffnet/suites/13469079922/artifacts/739158257
Let me know if it solves the issue!

**Comment by GyulyVGC** [comment] 2023-07-18 07:24
I'm closing since this issue has already been solved a number of times.

All you have to do is installing the version using the `glow` renderer.

Feel free to reopen the issue if you still have problems.

**Closed by GyulyVGC** 2023-07-18 07:24 UTC
Labels: duplicate, renderer

**Comment by wisehackermonkey** [comment] 2023-09-08 13:50
thanks!
