### ISSUE TITLE
SegFault when selecting Settings/Style

### ISSUE THREAD

**Issue by joepolcari** [GyulyVGC/sniffnet#355] opened 2023-08-24 19:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

When selecting Style in Settings, version 1.2.2, the app crashes. Running with strace shows segfault.

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

### Additional context

running on Linux Mint 21.2.
Installed Rust using synaptic then
sudo apt install libpcap-dev libfontconfig libfontconfig1-dev libasound2-dev
then downloaded Sniffnet_LinuxDEB_i386.deb from your github page and sudo apt installed it.
All with no errors.
Everything seems to work except the Style tab.

**Comment by joepolcari** [comment] 2023-08-24 19:09
Also this may help
rustc --version
rustc 1.66.1 (90743e729 2023-01-10) (built from a source tarball)

**Comment by GyulyVGC** [comment] 2023-08-25 07:21
I think it's due to the color gradients contained in that page.

The default renderer used (`wgpu`) sometimes has problems; you can try downloading the app from there: https://github.com/GyulyVGC/sniffnet/suites/14909529200/artifacts/849640693.

This is an alternative version of Sniffnet that uses a different graphical renderer (`tiny-skia`).
It should fix this issue.

**Comment by GyulyVGC** [comment] 2023-08-28 14:06
Closing the issue.
I was able to reproduce the issue on an older VM based on Linux.
I confirm that the problem is due to color gradients and can be solved using the `tiny-skia` renderer.

@joepolcari don't hesitate to reopen the issue if you still have doubts.

**Closed by GyulyVGC** 2023-08-28 14:06 UTC
Labels: renderer

**Comment by seppzer0** [comment] 2023-11-30 11:18
@GyulyVGC , hi!

The issue reproduces for me as well. I do run a Linux system in a VM, and when opening the "Style" section the app crashes.

More data on my side:
- OS (in VM) -> Elementary OS;
- Hypervisor -> Oracle VirtualBox 7.0.6.

The link to an `alternative version of Sniffnet` seems expired.

Is there maybe a setting I could switch in the Hypervisor/OS I'm using or will there be a fix for the Sniffnet itself in relation to this?

**Comment by GyulyVGC** [comment] 2023-11-30 11:30
Hi @seppzer0 

Try to set an environment variable `ICED_BACKEND=tiny-skia`.
This should automatically run the app using the other graphical renderer.
Otherwise, you can also download an updated version of Sniffnet from the links in the README, troubleshooting section.
I had to update the old links since they expire after 90 days.

**Comment by seppzer0** [comment] 2023-11-30 11:46
@GyulyVGC ,

> Try to set an environment variable ICED_BACKEND=tiny-skia
It worked, thank you!

> from the links in the README, [troubleshooting section](https://github.com/GyulyVGC/sniffnet#troubleshooting)
Understood, will use this for reference in future.
