### ISSUE TITLE
the procedure entry point pcap_set_immediate_mode could not be located in the dynamic link library

### ISSUE THREAD

**Issue by AriesAlex** [GyulyVGC/sniffnet#371] opened 2023-09-09 16:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

when opening app there's next error
the procedure entry point pcap_set_immediate_mode could not be located in the dynamic link library
![image](https://github.com/GyulyVGC/sniffnet/assets/39626061/b4db587c-774f-4bf5-81ea-d341a3bec094)
npcap installed

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment] 2023-09-09 21:17
Hi @AriesAlex 

As stated in other issues and written in the README, you have to

> Install [Npcap](https://npcap.com/#download), making sure to check the box `Install Npcap in WinPcap API-compatible Mode` during the installation.

This will solve your problem.

Closing this issue as it's a duplicate of others.

**Closed by GyulyVGC** 2023-09-09 21:17 UTC
