### ISSUE TITLE
SniffNet Install On Windows 7 SP1

### ISSUE THREAD

**Issue by kenrmayfield** [GyulyVGC/sniffnet#293] opened 2023-07-03 02:53 UTC
### What's the problem?

First of All.........Excellent Work Developing SniffNet.

I  Encountered a DLL Error after Installing SniffNet 1.2.1 64Bit on Windows 7 SP1 64Bit.   

The Error:  Entry Point Not Found and it is Referencing the DLL API-MS-WIN-CRT-STRING-L1-1-0.DLL
Yes......the DLL is in the System32 Directory.   I did have to Download the DLL from DLL-FILES.COM.

It seems that Windows 7 does not come with D3DCOMPILER_47.DLL or API-MS-WIN-CRT-STRING-L1-1-0.DLL 
I had to Download both 64Bit Files from DLL-FILES.COM when SniffNet Complained they were not Installed.

Is Windows 7 not Compatible with SniffNet?   

Thanks,
Kenneth

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment] 2023-07-03 08:00
Windows 7 is compatible with Sniffnet... does it give you the same error after installing the DLL?
Also, did you install Npcap? It shouldn't be related to your error, but it's a required dependency on Windows.

**Comment by kenrmayfield** [comment] 2023-07-03 08:29
Giuliano,

Yes I Installed Npcap 1.75.

That is what I was stating about the Error.....that I Installed the DLLs 
and still the Errors persist.

Thanks,
Kenneth

On 2023-07-03 3:01 am, Giuliano Bellini wrote:

> Windows 7 is compatible with Sniffnet... does it give you the same 
> error after installing the DLL?
> Also, did you install Npcap? It shouldn't be related to your error, but 
> it's a required dependency on Windows.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/GyulyVGC/sniffnet/issues/293#issuecomment-1617574930
[2]

**Comment by kenrmayfield** [comment] 2023-07-04 13:52
Can you tell me what Versions of NPCAP and Sniffnet you used for your 
Testing?

What Versions of Windows did you Test?

Thanks,
Kenneth

On 2023-07-04 2:54 am, Giuliano Bellini wrote:

> I'm sorry but I was not able to reproduce this error in any of the 
> Windows systems I tried.
> I don't know you what to suggest if not to search online if other 
> people incurred in the same error before.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/GyulyVGC/sniffnet/issues/293#issuecomment-1619724785
[2]

**Comment by GyulyVGC** [comment] 2023-07-04 14:53
> Can you tell me what Versions of NPCAP and Sniffnet you used for your Testing? What Versions of Windows did you Test? 

I personally tested it on Windows 8/10/11.

But I know people that run it successfully on Windows 7 (for example: https://github.com/GyulyVGC/sniffnet/issues/108).

The latest NPCAP & Sniffnet version should be fine.

As mentioned in the issue I linked, I build the binary and the installer in the latest Windows version so it may cause some problems, even though usually don't.
If you want to be more sure you can clone the repo and build from source (requires a Rust installation).
If you choose to follow this path and are not familiar with Rust, just let me know and I can help you.

**Comment by kenrmayfield** [comment] 2023-07-05 01:15
Giuliano,

Can you Build from Windows 7 SP1 and Upload the Installer?

On 2023-07-04 9:53 am, Giuliano Bellini wrote:

>> Can you tell me what Versions of NPCAP and Sniffnet you used for your 
>> Testing? What Versions of Windows did you Test?
> 
> I personally tested it on Windows 8/10/11.
> 
> But I know people that run it successfully on Windows 7 (for example: 
> #108 [1]).
> 
> The latest NPCAP & Sniffnet version should be fine.
> 
> As mentioned in the issue I linked, I build the binary and the 
> installer in the latest Windows version so it may cause some problems, 
> even though usually don't.
> If you want to be more sure you can clone the repo and build from 
> source (requires a Rust installation).
> If you choose to follow this path and are not familiar with Rust, just 
> let me know and I can help you.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/GyulyVGC/sniffnet/issues/108
[2] 
https://github.com/GyulyVGC/sniffnet/issues/293#issuecomment-1620399870
[3]

**Comment by kenrmayfield** [comment] 2023-07-05 01:41
Giuliano,

Can you Build from Windows 7 SP1 and Upload the Installer?

Are these Two Dll's from the Installer for SniffNet: D3DCOMPILER_47.DLL 
or API-MS-WIN-CRT-STRING-L1-1-0.DLL?

As mentioned before,  SniffNet Complains about these Two DLL's are 
missing.   I did state before that I Installed the Missing DLL's however 
I still got the Error: Entry Point Not Found and it is Referencing the 
DLL API-MS-WIN-CRT-STRING-L1-1-0.DLL

Yes I did Install the appropriate Version of the DLL's which would be 
x64Bit for Windows 7 SP1 x64Bit.

Let me be clear.........The Software will Install however when you Run 
SniffNet on  Windows 7 SP1 x64Bit.......
I Receive the Error as Mentioned.

On 2023-07-04 9:53 am, Giuliano Bellini wrote:

>> Can you tell me what Versions of NPCAP and Sniffnet you used for your 
>> Testing? What Versions of Windows did you Test?
> 
> I personally tested it on Windows 8/10/11.
> 
> But I know people that run it successfully on Windows 7 (for example: 
> #108 [1]).
> 
> The latest NPCAP & Sniffnet version should be fine.
> 
> As mentioned in the issue I linked, I build the binary and the 
> installer in the latest Windows version so it may cause some problems, 
> even though usually don't.
> If you want to be more sure you can clone the repo and build from 
> source (requires a Rust installation).
> If you choose to follow this path and are not familiar with Rust, just 
> let me know and I can help you.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/GyulyVGC/sniffnet/issues/108
[2] 
https://github.com/GyulyVGC/sniffnet/issues/293#issuecomment-1620399870
[3]

**Comment by GyulyVGC** [comment] 2023-07-05 05:55
Unluckily I'm unable to build on Windows 7 now...
As I said you could build yourself with cargo (installing Rust and the required build tools)
I'm sorry this problem occurred but I don't know what to suggest if you already installed the corresponding DLL

There you can also find the corresponding scoop package, where the guy of the other issue successfully installed the app: https://scoop.sh/#/apps?q=Sniffnet

**Comment by kenrmayfield** [comment] 2023-09-02 01:51
@GyulyVGC,

Do you have Time to Build for Windows 7?

**Comment by GyulyVGC** [comment] 2023-09-02 14:41
I'd have the time, but not a Windows 7 installation.
Moreover, I doubt it would solve this particular problem.

**Comment by bt4ibwem8** [comment] 2024-07-24 11:12
The newest version failed to start on win7 (version 1.3.0 works fine):

![image](https://github.com/user-attachments/assets/0052ee55-edd1-4a28-bc9a-58a89b83c1b5)

**Comment by GyulyVGC** [comment] 2024-07-24 11:19
> The newest version failed to start on win7 (version 1.3.0 works fine):
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/0052ee55-edd1-4a28-bc9a-58a89b83c1b5)
> 
> 

Hi @bt4ibwem8 can you try to launch the Sniffnet executable from terminal and post here what you get, thanks

**Comment by bt4ibwem8** [comment] 2024-07-24 13:24
i get the same error

**Comment by bt4ibwem8** [comment] 2024-07-24 13:42
it is the same window which i posted... directly in cmd i get nothing

**Comment by GyulyVGC** [comment] 2024-07-24 14:07
I'd be glad to help but I can't without a backtrace of the problem.

**Comment by bt4ibwem8** [comment] 2024-07-24 21:55
Sniffnet can be run also in terminal with some commands? Because on version 1.3.0 it just run normal window of Sniffnet (when i type "sniffnet" in cmd).

**Comment by GyulyVGC** [comment] 2024-07-25 18:53
> Sniffnet can be run also in terminal with some commands? Because on version 1.3.0 it just run normal window of Sniffnet (when i type "sniffnet" in cmd).

Oh, you are right.
I now remember that on macOS and Linux, the terminal launching Sniffnet keeps running, but on Windows I close it because otherwise even when running the app by clicking on its icon, a terminal was kept open.

But in this way now we're not able to see terminal messages... mmh I will think to a workaround and let you know.

**Comment by bt4ibwem8** [comment] 2024-07-30 07:54
I am not using antivirus. `sfc /scannow` did not help me. When i enable VxKex, i get many dll errors. I copied DLLs to system32 but for this one it still complains:

![image](https://github.com/user-attachments/assets/3ebedec4-9fce-4e18-9cad-4b47b598f5ad)

**Comment by GyulyVGC** [comment] 2024-07-30 08:54
@bt4ibwem8 I've tried building a new Sniffnet Installer including the compilation flag `-C target-feature=+crt-static`, which should solve some DLL issues.
Can you try it and let me know if the problem is solved? Thanks in advance.

64-bit Installer: [Sniffnet_Windows_64-bit.msi.zip](https://github.com/user-attachments/files/16424909/Sniffnet_Windows_64-bit.msi.zip)
32-bit Installer: [Sniffnet_Windows_32-bit.msi.zip](https://github.com/user-attachments/files/16424914/Sniffnet_Windows_32-bit.msi.zip)

**Comment by bt4ibwem8** [comment] 2024-07-30 09:37
i still get the same error

**Comment by GyulyVGC** [comment] 2024-08-02 08:50
I will try to set up a Windows 7 installation and hope I can reproduce your issue.
Anyway, be careful that the current Sniffnet Installer doesn't remove previous installed versions.
By default, the latest one is launched, but the one I provided you in the message above has the same tag as the latest release, so be sure to delete all the previous versions before trying with that.

**Comment by bt4ibwem8** [comment] 2024-08-19 18:17
if Vxkex is disabled, i get this error:

![image](https://github.com/user-attachments/assets/606ff7ff-be8e-4a37-9859-03214d5f91c0)

**Comment by cfy3133** [comment] 2024-08-21 02:15
I also encountered the same problem.
![image](https://github.com/user-attachments/assets/5187735c-739d-4682-9111-307b7de010fe)

**Comment by GyulyVGC** [comment] 2024-08-21 08:59
> I also encountered the same problem.
> ![image](https://private-user-images.githubusercontent.com/43978367/359723582-5187735c-739d-4682-9111-307b7de010fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzA5MjYsIm5iZiI6MTcyNDIzMDYyNiwicGF0aCI6Ii80Mzk3ODM2Ny8zNTk3MjM1ODItNTE4NzczNWMtNzM5ZC00NjgyLTkxMTEtMzA3YjdkZTAxMGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA4NTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzODdlMDg5ZGRmMGY4NDlhY2E3NDFmODQyMDdkZDNmODBmY2MzODcxODhmMzMwMTk5NDhjYTc0OGVhOGUzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3WIG4TL58hmvCqNNqIYk6mDN_wVaxuch8h9jfUdklJE)

Hi @cfy3133, this is not the same issue.
Check #371 to see how to solve your problem... it was already solved multiple times in the past.

**Comment by andyzdev** [comment] 2024-09-15 06:33
I hope you fix this bug one day. I have the same problem on my Win7. 

error code 0xc0000005

**Comment by GyulyVGC** [comment] 2024-12-14 00:16
I'm closing this issue since nowadays the oldest version to receive Tier 1 support from Rust is Windows 10:
> Rust 1.75 will be the last to officially support Windows 7, 8 and 8.1. 
> Support for Windows versions before 10 will end in February 2024 with Rust 1.76.

See https://github.com/rust-lang/compiler-team/issues/651 for more info.

**Closed by GyulyVGC** 2024-12-14 00:16 UTC
Labels: bug, missing dependency, Windows

**Comment by kenrmayfield** [comment] 2024-12-15 03:19
@bt4ibwem8 
@andyzdev 
@cfy3133 

GyulyVGC,

So with Rust 1.75 did you Test on Windows 7 like you stated on August 2, 2024?

Reason why I am asking is because I Open this Ticket July 2 2023.

Now that Rust 1.75 Ends Support for Windows 7,8,8.1.....................the Answer is Your Closing the Ticket?

Irregardless that Rust 1.75 Ends Support for Windows 7,8,8.1...............Your the Developer of SniffNet and Issues have been provided to You about the Errors with Windows 7 since July 2 2023.

That just does not Look Good for instance if someone like Microsoft wanted to make you a Deal and Market Your Product in the Windows OS.

If SniffNet is not Supported on Windows 7,8,8.1 or you had No Plans for Windows 7,8,8.1 from the Start then it could have been stated on the Repo, SniffNet WebSite and Documentation.

However telling Users to Install this DLL, Use Scoope and Etc and Users stating it is not working since July 3, 2023...................but You never giving Results on Your Testing of Windows 7,8,8.1.

Again...............now that Rust 1.76 the Conclusion is Windows 7,8,8.1 is not Support and Closing the Ticket.

**Comment by GyulyVGC** [comment] 2024-12-15 06:47
I'm really sorry for this but as you can imagine this isn't something that only depends on myself.

If even Microsoft and Rust are ending support for it, this only makes it even more difficult for me to find a fix.

I'd like to support as more environments as I can; however this isn't always possible.

**Comment by bt4ibwem8** [comment] 2024-12-15 15:08
should it work if i replace that .dll from win10 system?

![image](https://github.com/user-attachments/assets/74644b10-9d22-4ef8-8d60-9aff80703f83)

**Comment by GyulyVGC** [comment] 2024-12-15 16:03
You can try but I don't believe so.
