### ISSUE TITLE
wpcap.dll not found

### ISSUE THREAD

**Issue by brian316** [GyulyVGC/sniffnet#565] opened 2024-07-20 00:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

![image](https://github.com/user-attachments/assets/27720030-408a-4681-8b41-c13873133071)

error on install. windows 11

fix is install this https://npcap.com/#download

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment] 2024-07-20 19:47
Hi @brian316
 
> fix is install this https://npcap.com/#download

From this comment I understand that you probably already fixed the issue.
Yes, the solution is to install Npcap on Windows, as documented in the [Sniffnet Wiki](https://github.com/GyulyVGC/sniffnet/wiki).

This is also a duplicate of many other issues, so I'm closing it as solved.

**Closed by GyulyVGC** 2024-07-20 19:47 UTC
Labels: duplicate, missing dependency, Windows
