### ISSUE TITLE
prcap_set_immendiate_mode not found in exe

### ISSUE THREAD

**Issue by C0kkie** [GyulyVGC/sniffnet#200] opened 2023-05-20 10:28 UTC
**Describe the bug**
If i want to start the programm after installation i get the message, that it cant find prcap_set_immendiate_mode  in sniffnet.exe

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. Install Programm on Windows 11
2. Start exe

**Expected behavior**
Programm should start

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser: Chrome

**Comment by GyulyVGC** [comment] 2023-05-20 10:31
Hi @C0kkie 
This issue has already been solved: https://github.com/GyulyVGC/sniffnet/issues/86

Please let me know in case of further doubts or if you have other problems.
Also make sure you have installed the required dependencies.

**Comment by C0kkie** [comment] 2023-05-20 10:41
@GyulyVGC but why does it not work in [v1.2.0](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.2.0) then

**Comment by GyulyVGC** [comment] 2023-05-20 10:43
It's a problem related to Npcap which can be solved by yourself when you install it.

You have to read #86 for more info.

**Comment by GyulyVGC** [comment] 2023-05-21 17:36
Closing as duplicate of #21, #86, #211 which have already been solved.
I've also updated the docs to make it more clear: 38c3e3a

**Closed by GyulyVGC** 2023-05-21 17:36 UTC
Labels: duplicate
